# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseAssets(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Assets']] = 'Assets'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetsActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetsActions[_PrismaModelT](client or get_client(), cls)


class BaseAssetsImage(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssetsImage']] = 'AssetsImage'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetsImageActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetsImageActions[_PrismaModelT](client or get_client(), cls)


class BaseAssetsDocument(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssetsDocument']] = 'AssetsDocument'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetsDocumentActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetsDocumentActions[_PrismaModelT](client or get_client(), cls)


class BaseCategory(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Category']] = 'Category'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CategoryActions[_PrismaModelT]':
        from .client import get_client

        return actions.CategoryActions[_PrismaModelT](client or get_client(), cls)


class BaseSubCategory(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SubCategory']] = 'SubCategory'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SubCategoryActions[_PrismaModelT]':
        from .client import get_client

        return actions.SubCategoryActions[_PrismaModelT](client or get_client(), cls)


class BaseEmployeeUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['EmployeeUser']] = 'EmployeeUser'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.EmployeeUserActions[_PrismaModelT]':
        from .client import get_client

        return actions.EmployeeUserActions[_PrismaModelT](client or get_client(), cls)


class BaseAssetsCheckout(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssetsCheckout']] = 'AssetsCheckout'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetsCheckoutActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetsCheckoutActions[_PrismaModelT](client or get_client(), cls)


class BaseAssetsCheckin(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssetsCheckin']] = 'AssetsCheckin'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetsCheckinActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetsCheckinActions[_PrismaModelT](client or get_client(), cls)


class BaseAssetsMove(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssetsMove']] = 'AssetsMove'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetsMoveActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetsMoveActions[_PrismaModelT](client or get_client(), cls)


class BaseAssetsReserve(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssetsReserve']] = 'AssetsReserve'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetsReserveActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetsReserveActions[_PrismaModelT](client or get_client(), cls)


class BaseAssetsLease(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssetsLease']] = 'AssetsLease'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetsLeaseActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetsLeaseActions[_PrismaModelT](client or get_client(), cls)


class BaseAssetsLeaseReturn(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssetsLeaseReturn']] = 'AssetsLeaseReturn'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetsLeaseReturnActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetsLeaseReturnActions[_PrismaModelT](client or get_client(), cls)


class BaseAssetsDispose(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssetsDispose']] = 'AssetsDispose'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetsDisposeActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetsDisposeActions[_PrismaModelT](client or get_client(), cls)


class BaseAssetsMaintenance(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssetsMaintenance']] = 'AssetsMaintenance'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetsMaintenanceActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetsMaintenanceActions[_PrismaModelT](client or get_client(), cls)


class BaseMaintenanceInventoryItem(_PrismaModel):
    __prisma_model__: ClassVar[Literal['MaintenanceInventoryItem']] = 'MaintenanceInventoryItem'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.MaintenanceInventoryItemActions[_PrismaModelT]':
        from .client import get_client

        return actions.MaintenanceInventoryItemActions[_PrismaModelT](client or get_client(), cls)


class BaseAssetsAuditHistory(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssetsAuditHistory']] = 'AssetsAuditHistory'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetsAuditHistoryActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetsAuditHistoryActions[_PrismaModelT](client or get_client(), cls)


class BaseAssetsHistoryLogs(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssetsHistoryLogs']] = 'AssetsHistoryLogs'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetsHistoryLogsActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetsHistoryLogsActions[_PrismaModelT](client or get_client(), cls)


class BaseAssetUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssetUser']] = 'AssetUser'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetUserActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetUserActions[_PrismaModelT](client or get_client(), cls)


class BaseFileHistory(_PrismaModel):
    __prisma_model__: ClassVar[Literal['FileHistory']] = 'FileHistory'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.FileHistoryActions[_PrismaModelT]':
        from .client import get_client

        return actions.FileHistoryActions[_PrismaModelT](client or get_client(), cls)


class BaseReturnForm(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ReturnForm']] = 'ReturnForm'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ReturnFormActions[_PrismaModelT]':
        from .client import get_client

        return actions.ReturnFormActions[_PrismaModelT](client or get_client(), cls)


class BaseAccountabilityForm(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AccountabilityForm']] = 'AccountabilityForm'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AccountabilityFormActions[_PrismaModelT]':
        from .client import get_client

        return actions.AccountabilityFormActions[_PrismaModelT](client or get_client(), cls)


class BaseAssetsLocation(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssetsLocation']] = 'AssetsLocation'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetsLocationActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetsLocationActions[_PrismaModelT](client or get_client(), cls)


class BaseAssetsSite(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssetsSite']] = 'AssetsSite'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetsSiteActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetsSiteActions[_PrismaModelT](client or get_client(), cls)


class BaseAssetsDepartment(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssetsDepartment']] = 'AssetsDepartment'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetsDepartmentActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetsDepartmentActions[_PrismaModelT](client or get_client(), cls)


class BaseInventoryItem(_PrismaModel):
    __prisma_model__: ClassVar[Literal['InventoryItem']] = 'InventoryItem'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.InventoryItemActions[_PrismaModelT]':
        from .client import get_client

        return actions.InventoryItemActions[_PrismaModelT](client or get_client(), cls)


class BaseInventoryTransaction(_PrismaModel):
    __prisma_model__: ClassVar[Literal['InventoryTransaction']] = 'InventoryTransaction'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.InventoryTransactionActions[_PrismaModelT]':
        from .client import get_client

        return actions.InventoryTransactionActions[_PrismaModelT](client or get_client(), cls)


class BaseCompanyInfo(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CompanyInfo']] = 'CompanyInfo'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CompanyInfoActions[_PrismaModelT]':
        from .client import get_client

        return actions.CompanyInfoActions[_PrismaModelT](client or get_client(), cls)


class BaseAssetSchedule(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssetSchedule']] = 'AssetSchedule'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssetScheduleActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssetScheduleActions[_PrismaModelT](client or get_client(), cls)


class BaseAutomatedReportSchedule(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AutomatedReportSchedule']] = 'AutomatedReportSchedule'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AutomatedReportScheduleActions[_PrismaModelT]':
        from .client import get_client

        return actions.AutomatedReportScheduleActions[_PrismaModelT](client or get_client(), cls)


