from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Assets',
    'AssetsImage',
    'AssetsDocument',
    'Category',
    'SubCategory',
    'EmployeeUser',
    'AssetsCheckout',
    'AssetsCheckin',
    'AssetsMove',
    'AssetsReserve',
    'AssetsLease',
    'AssetsLeaseReturn',
    'AssetsDispose',
    'AssetsMaintenance',
    'MaintenanceInventoryItem',
    'AssetsAuditHistory',
    'AssetsHistoryLogs',
    'AssetUser',
    'FileHistory',
    'ReturnForm',
    'AccountabilityForm',
    'AssetsLocation',
    'AssetsSite',
    'AssetsDepartment',
    'InventoryItem',
    'InventoryTransaction',
    'CompanyInfo',
    'AssetSchedule',
    'AutomatedReportSchedule',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Assets': {
        'category': 'Category',
        'subCategory': 'SubCategory',
        'checkouts': 'AssetsCheckout',
        'checkins': 'AssetsCheckin',
        'moves': 'AssetsMove',
        'reservations': 'AssetsReserve',
        'leases': 'AssetsLease',
        'leaseReturns': 'AssetsLeaseReturn',
        'disposals': 'AssetsDispose',
        'maintenances': 'AssetsMaintenance',
        'auditHistory': 'AssetsAuditHistory',
        'historyLogs': 'AssetsHistoryLogs',
        'schedules': 'AssetSchedule',
    },
    'AssetsImage': {
    },
    'AssetsDocument': {
    },
    'Category': {
        'subCategories': 'SubCategory',
        'assets': 'Assets',
    },
    'SubCategory': {
        'category': 'Category',
        'assets': 'Assets',
    },
    'EmployeeUser': {
        'checkouts': 'AssetsCheckout',
        'checkins': 'AssetsCheckin',
        'moves': 'AssetsMove',
        'reservations': 'AssetsReserve',
        'returnForms': 'ReturnForm',
        'accountabilityForms': 'AccountabilityForm',
    },
    'AssetsCheckout': {
        'asset': 'Assets',
        'employeeUser': 'EmployeeUser',
        'checkins': 'AssetsCheckin',
    },
    'AssetsCheckin': {
        'asset': 'Assets',
        'checkout': 'AssetsCheckout',
        'employeeUser': 'EmployeeUser',
    },
    'AssetsMove': {
        'asset': 'Assets',
        'employeeUser': 'EmployeeUser',
    },
    'AssetsReserve': {
        'asset': 'Assets',
        'employeeUser': 'EmployeeUser',
    },
    'AssetsLease': {
        'asset': 'Assets',
        'returns': 'AssetsLeaseReturn',
    },
    'AssetsLeaseReturn': {
        'asset': 'Assets',
        'lease': 'AssetsLease',
    },
    'AssetsDispose': {
        'asset': 'Assets',
    },
    'AssetsMaintenance': {
        'asset': 'Assets',
        'inventoryItems': 'MaintenanceInventoryItem',
    },
    'MaintenanceInventoryItem': {
        'maintenance': 'AssetsMaintenance',
        'inventoryItem': 'InventoryItem',
    },
    'AssetsAuditHistory': {
        'asset': 'Assets',
    },
    'AssetsHistoryLogs': {
        'asset': 'Assets',
    },
    'AssetUser': {
    },
    'FileHistory': {
    },
    'ReturnForm': {
        'employeeUser': 'EmployeeUser',
    },
    'AccountabilityForm': {
        'employeeUser': 'EmployeeUser',
    },
    'AssetsLocation': {
    },
    'AssetsSite': {
    },
    'AssetsDepartment': {
    },
    'InventoryItem': {
        'transactions': 'InventoryTransaction',
        'maintenanceUsages': 'MaintenanceInventoryItem',
    },
    'InventoryTransaction': {
        'inventoryItem': 'InventoryItem',
        'relatedTransaction': 'InventoryTransaction',
        'transferTransactions': 'InventoryTransaction',
    },
    'CompanyInfo': {
    },
    'AssetSchedule': {
        'asset': 'Assets',
    },
    'AutomatedReportSchedule': {
    },
}

# fmt: on